[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'scwood/vim-hybrid'
hook_add = '''
	syntax on
	set background=dark
	colorscheme hybrid
'''

[[plugins]]
repo = 'mhinz/vim-startify'
hook_add = '''
	setlocal nospell
	let g:startify_custom_header = [
		\ '						Keybindings',
		\ '	Function Keys (Work in normal- and inputmode):',
		\ '	F1		=> Menu					F2		=> Filebrowser',
		\ '	F3		=> Tagbar				F4		=> Bufferlist',
		\ '	F5		=> Undotree				F6		=> Extradite',
		\ '	F7		=> Undefined			F8		=> NoSigns',
		\ '	F9		=> TaskList				F10		=> Register/Yankhistory',
		\ '	F11		=> SpellToggle			F12		=> UnsavedDiff',
		\ '',
		\ '	Other Keys:',
		\ '	,		=> <Leader>				<C-p>	=> Unite FuzzyFileFinder',
		\ '	<C-f>	=> Unite Grep			<C-h>	=> Unite Search Help',
		\ '	<C-e>	=> Fill snippet',
		\ '',
		\ '',
		\ ]
'''

[[plugins]]
repo = 'haya14busa/dein-command.vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add  = '''
	autocmd BufReadPost fugitive://* set bufhidden=delete
	autocmd BufReadPost fugitive://*
				\ if fugitive#buffer().type() =~# '^\%(tree\|blob\)$' |
				\   nnoremap <buffer> .. :edit %:h<CR> |
				\ endif
'''

[[plugins]]
repo = 'tpope/vim-git'

[[plugins]]
repo = 'tpope/vim-surround'
hook_add = '''
	nmap <silent>sa <Plug>(operator-surround-append)
	nmap <silent>sd <Plug>(operator-surround-delete)
	nmap <silent>sr <Plug>(operator-surround-replace)
'''

[[plugins]]
repo = 'tpope/vim-ragtag'

[[plugins]]
repo = 'tpope/vim-repeat'
mappings = '.'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'mbbill/undotree'
hook_add  = '''
	nnoremap <silent> <F5> :UndotreeToggle<CR>
	:imap <F5> <C-o>:UndotreeToggle<CR>
'''
hook_source  = 'source ~/.vim/rc/plugins/undotree.rc.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
	let g:tagbar_singleclick = 1
	let g:tagbar_sort = 0
	nnoremap <silent> <F3> :<C-u>TagbarToggle<CR>
	:imap <silent> <F3> <C-o>:<C-u>TagbarToggle<CR>
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
	let g:airline#extensions#tabline#enabled = 1
	let g:airline#extensions#tabline#show_buffers = 1
	let g:airline_powerline_fonts = 1
	let g:airline_theme="dark"
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = 'vim-airline/vim-airline'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_add  = '''
	let g:extra_whitespace_ignored_filetypes = ['unite', 'vimfiler', 'vimshell', 'Help', 'vimfiler:explorer', 'startify']
'''

[[plugins]]
repo = 'gregsexton/MatchTag'

[[plugins]]
repo = 'vim-scripts/delimitMate.vim'

[[plugins]]
repo = 'xolox/vim-misc'

[[plugins]]
repo = 'xolox/vim-easytags'
depends = 'xolox/vim-misc'
hook_add  =  '''
	let g:easytags_dynamic_files = 1
	let g:easytags_resolve_links = 1
	let g:easytags_include_members = 1
	let g:easytags_autorecurse = 0
	let g:easytags_async = 1
	let g:easytags_auto_highlight = 0
	let g:easytags_updatetime_warn = 0

	function! UpdateProjectTags()
		let g:easytags_autorecurse = 1
		:UpdateTags
		let g:easytags_autorecurse = 0
	endfunction

	nnoremap <leader>ut :<C-u>call UpdateProjectTags()<CR>
'''

[[plugins]]
repo = 'pbrisbin/vim-mkdir'

[[plugins]]
repo = 'jmcantrell/vim-diffchanges'
hook_add  =  '''
	nnoremap <silent> <F12> :DiffChangesDiffToggle<CR>
	inoremap <silent> <F12> <C-o>:<C-u>DiffChangesDiffToggle<CR>
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'zhaocai/DirDiff.vim'

[[plugins]]
repo = 'ap/vim-css-color'

[[plugins]]
repo = 'vim-scripts/bufkill.vim'

[[plugins]]
repo = 'mhinz/vim-signify'
hook_add  = '''
	let g:signify_vcs_list = [ 'svn', 'hg', 'bzr' ]
	let signify_update_on_focusgained = 1
	let g:signify_sign_add               = '+'
	let g:signify_sign_delete            = '_'
	let g:signify_sign_delete_first_line = '‾'
	let g:signify_sign_change            = '~'
	let g:signify_sign_changedelete      = '~_'
'''

[[plugins]]
repo = 'int3/vim-extradite'
depends = 'tpope/vim-fugitive'
hook_add  =  '''
	nnoremap <silent> <F6> :Extradite!<CR>
	:inoremap <F6> <C-o>:<C-u>Extradite!<CR>
'''

[[plugins]]
repo = 'airblade/vim-rooter'
hook_add  =  '''
	let g:rooter_silent_chdir = 1
	let g:rooter_change_directory_for_non_project_files = 'current'
'''

[[plugins]]
repo = 'jreybert/file-line'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'vitalk/vim-shebang'

[[plugins]]
repo = 'vimwiki/vimwiki'
hook_add = '''
	nnoremap <silent><Leader>wf :<C-u>call vimwiki#base#follow_link('nosplit')<CR>
	nnoremap <silent><Leader>wv :<C-u>call vimwiki#base#follow_link('vsplit')<CR>
	nnoremap <silent><Leader>wb :<C-u>call vimwiki#base#go_back_link()<CR>
'''
