[[plugins]]
repo = 'Shougo/tabpagebuffer.vim'
on_if = 'tabpagenr() > 1'

[[plugins]]
repo = 'Shougo/neopairs.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_if = 1

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_if = 1
on_source = 'unite.vim'

[[plugins]]
repo = 'thinca/vim-unite-history'
on_source = 'unite.vim'

[[plugins]]
repo = 'osyo-manga/unite-filetype'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/unite-sudo'
on_source = ['unite.vim', 'vimfiler.vim']

[[plugins]]
repo = 'zyphrus/unite-tasklist'
on_source = 'unite.vim'
hook_add  = '''
	let g:unite_tasklist_ignorecase = 1
	let g:unite_tasklist_tokens = [
		\ 'CAUTION',
		\ 'FIXME',
		\ 'HACK',
		\ 'PATCH',
		\ 'TBD',
		\ 'TODO',
		\ 'XXX',
		\]
'''

[[plugins]]
repo = 'scrooloose/syntastic'
hook_add = '''
	let g:airline#extensions#syntastic#enabled = 1
	let g:syntastic_always_populate_loc_list = 1
	let g:syntastic_auto_loc_list = 1
	let g:syntastic_check_on_open = 1
	let g:syntastic_enable_signs = 1
	let g:syntastic_check_on_wq = 0
'''

[[plugins]]
repo = 'Shougo/unite.vim'
depends = ['neomru.vim', 'tabpagebuffer.vim']
on_event = 'VimEnter'
hook_source = '''
	source ~/.vim/rc/plugins/unite.rc.vim
	nnoremap <silent> <F1> :<C-u>Unite -profile-name=menu menu:Main<CR>
	inoremap <silent> <F1> <C-o>:<C-u>Unite -profile-name=menu menu:Main<CR>
	nnoremap <silent> <F4> :<C-u>Unite buffer -toggle<CR>
	inoremap <silent> <F4> <C-o>:<C-u>Unite buffer -toggle<CR>
	nnoremap <silent> <F9> :<C-u>Unite tasklist -toggle -start-insert -vertical -winwidth=40<CR>
	inoremap <silent> <F9> <C-o>:<C-u>Unite tasklist -toggle -start-insert -vertical -winwidth=40<CR>
	nnoremap <silent> <C-P> :<C-u>Unite -buffer-name=files -toggle -start-insert neomru/file file_rec/async:!<CR>
	nnoremap <silent> <C-f> :<C-u>Unite grep:. -buffer-name=grep%".tabpagenr()." -toggle -auto-preview -no-split -no-empty<CR>
	inoremap <silent> <F10> <C-o>:<C-u>Unite -buffer-name=register -toggle register history/yank<CR>
	nnoremap <silent> <F10> :<C-u>Unite -buffer-name=register -toggle register history/yank<CR>

	nnoremap <silent> [Space]ft
		\ :<C-u>Unite -start-insert filetype filetype/new<CR>

	" Tag jump.
	nnoremap <silent><expr> tt  &filetype == 'help' ?  "g\<C-]>" :
		\ ":\<C-u>UniteWithCursorWord -buffer-name=tag -immediately
		\  tag tag/include\<CR>"
	nnoremap <silent><expr> tp  &filetype == 'help' ?
		\ ":\<C-u>pop\<CR>" : ":\<C-u>Unite jump\<CR>"

	" Execute help.
	nnoremap <silent> <C-h>  :<C-u>Unite -buffer-name=help help<CR>

	" Search.
	nnoremap <silent> /
		\ :<C-u>Unite -buffer-name=search%`bufnr('%')`
		\ -start-insert line:forward:wrap<CR>
	nnoremap <silent> *
		\ :<C-u>UniteWithCursorWord -buffer-name=search%".bufnr('%')."
		\ line:forward:wrap<CR>
	nnoremap <silent> ?
		\ :<C-u>Unite -buffer-name=search%".bufnr('%')."
		\ -start-insert line:backward<CR>
	nnoremap [Alt]/       /
	nnoremap [Alt]?       ?
	nnoremap <silent> n
		\ :<C-u>UniteResume search%`bufnr('%')`
		\  -no-start-insert -force-redraw<CR>
'''

[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'context_filetype.vim'
if = "has('lua')"
on_event = 'InsertEnter'
hook_source = '''
	let g:neocomplete#enable_at_startup = 1
	source ~/.vim/rc/plugins/neocomplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertCharPre'
on_ft = 'snippet'
hook_source = 'source ~/.vim/rc/plugins/neosnippet.rc.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/unite-build'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
on_map = {n = '<Plug>'}
on_if = "isdirectory(bufname('%'))"
hook_add  = '''
	nnoremap <silent> <F2> :<C-u>VimFilerExplorer -parent -explorer-columns=type:size:time -toggle -no-safe -winwidth=50<CR>
	:imap <silent> <F2> <C-o>:<C-u>VimFilerExplorer -parent -explorer-columns=type:size:time -toggle -no-safe -winwidth=50<CR>
'''
hook_source = 'source ~/.vim/rc/plugins/vimfiler.rc.vim'

[[plugins]]
repo = 'Shougo/vimshell.vim'
on_map = {n = '<Plug>'}
hook_add = '''
	nmap <C-@>  <Plug>(vimshell_switch)
	nnoremap !  q:VimShellExecute<Space>
'''
hook_source = 'source ~/.vim/rc/plugins/vimshell.rc.vim'

[[plugins]]
repo = 'Shougo/unite-help'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_ft = 'all'

[[plugins]]
repo = 'Shougo/unite-session'
on_source = 'unite.vim'

[[plugins]]
repo = 'kana/vim-niceblock'
on_map = {x = '<Plug>'}
hook_add = '''
  xmap I  <Plug>(niceblock-I)
  xmap A  <Plug>(niceblock-A)
'''

[[plugins]]
repo = 'ujihisa/vimshell-ssh'
on_ft = 'vimshell'

[[plugins]]
repo = 'yomi322/vim-gitcomplete'
on_ft = 'vimshell'

[[plugins]]
repo = 'vim-jp/vital.vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css', 'html', 'php']

[[plugins]]
repo = 'thinca/vim-qfreplace'
on_ft = ['unite', 'quickfix']

[[plugins]]
repo = 'thinca/vim-quickrun'
on_map = '<Plug>'
hook_add = 'nmap <silent> <Leader>r <Plug>(quickrun)'

[[plugins]]
repo = 'thinca/vim-ref'
on_map = {n = '<Plug>'}
hook_source = 'source ~/.vim/rc/plugins/ref.rc.vim'

[[plugins]]
repo = 'tsukkee/unite-tag'
on_source = 'unite.vim'

[[plugins]]
repo = 'kopischke/unite-spell-suggest'
on_source = 'unite.vim'

[[plugins]]
repo = 'mtscout6/vim-tagbar-css'
on_source = 'tagbar'

[[plugins]]
repo = 'ujihisa/neco-look'
on_source = ['neocomplete.vim', 'deoplete.nvim']

[[plugins]]
repo = 'ujihisa/unite-colorscheme'
on_source = 'unite.vim'

[[plugins]]
repo = 'osyo-manga/unite-quickfix'
on_source = 'unite.vim'

[[plugins]]
repo = 'kana/vim-tabpagecd'
unite_sources = 'tab'

[[plugins]]
repo = 'godlygeek/csapprox'

[[plugins]]
repo = 'thinca/vim-guicolorscheme'

[[plugins]]
repo = 'bkad/CamelCaseMotion'
on_map = ['<Plug>CamelCaseMotion_w', '<Plug>CamelCaseMotion_b']

[[plugins]]
repo = 'syngan/vim-vimlint'
depends = 'ynkdir/vim-vimlparser'

# Operators
[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-operator-replace'
depends = 'kana/vim-operator-user'
on_map = [['nx', '<Plug>']]

[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = 'kana/vim-operator-user'
on_map = '<Plug>'

[[plugins]]
repo = 'chikatoike/concealedyank.vim'
on_map = [['x', '<Plug>(operator-concealedyank)']]

# Textobjs
[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'osyo-manga/vim-textobj-multiblock'
depends = 'kana/vim-textobj-user'
on_map = [['ox', '<Plug>']]

[[plugins]]
repo = 'AndrewRadev/sideways.vim'
on_map = [['ox', '<Plug>']]

[[plugins]]
repo = 'lambdalisue/vim-gita'
commands = 'Gita'

[[plugins]]
repo = 'lambdalisue/vim-gista'
on_map = {n = '<Plug>'}
hook_add = '''
  let g:gista#github_user = 'NemesisRE'
  let g:gista#directory = expand('$CACHE/gista')
'''

[[plugins]]
repo = 'shawncplus/phpcomplete.vim'
on_ft = ['php','ctp']

[[plugins]]
repo = 'ujihisa/unite-locate'
on_source = 'unite.vim'
unite_sources = 'locate'

[[plugins]]
repo = 'chrisbra/csv.vim'
on_ft = 'csv'

[[plugins]]
repo = 'spf13/PIV'
on_ft = ['php','ctp']
hook_add  = '''
	let g:DisableAutoPHPFolding=1
'''

[[plugins]]
repo = 'kovetskiy/vim-bash'
on_ft = 'sh'

[[plugins]]
repo = 'medihack/sh.vim'
on_ft = 'sh'
hook_add = '''
	let g:sh_indent_case_labels=1
'''

[[plugins]]
repo = 'vim-scripts/SQLComplete.vim'
on_ft = 'sql'

[[plugins]]
repo = 'violetyk/cake.vim'
on_ft = ['php','ctp']

[[plugins]]
repo = 'bigbrozer/vim-nagios'
on_ft = 'ruby'

[[plugins]]
repo = 'saltstack/salt-vim'
on_ft = 'salt'

[[plugins]]
repo = 'klen/python-mode'
on_ft = 'python'
