[[plugins]]
repo = 'Shougo/tabpagebuffer.vim'
on_if = 'tabpagenr() > 1'

[[plugins]]
repo = 'Shougo/neopairs.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_if = 1

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_if = 1
on_event = 'TextYankPost'
on_source = ['unite.vim', 'denite.nvim']

[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'context_filetype.vim'
if = "has('lua')"
on_event = 'InsertEnter'
hook_source = '''
	let g:neocomplete#enable_at_startup = 1
	source $RC_PATH/plugins/neocomplete.rc.vim
'''

[[plugins]]
repo = 'thinca/vim-unite-history'
on_source = 'unite.vim'

[[plugins]]
repo = 'osyo-manga/unite-filetype'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/unite-sudo'
on_source = ['unite.vim', 'vimfiler.vim']

[[plugins]]
repo = 'zyphrus/unite-tasklist'
on_source = 'unite.vim'
hook_add  = '''
	let g:unite_tasklist_ignorecase = 1
	let g:unite_tasklist_tokens = [
		\ 'CAUTION',
		\ 'FIXME',
		\ 'HACK',
		\ 'PATCH',
		\ 'TBD',
		\ 'TODO',
		\ 'XXX',
		\]
'''

[[plugins]]
repo = 'Shougo/unite-build'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/unite-help'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_ft = 'all'

[[plugins]]
repo = 'Shougo/unite-session'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/echodoc.vim'
on_event = 'CompleteDone'
hook_source = '''
	let g:echodoc#type = 'signature'
	call echodoc#enable()
'''

[[plugins]]
repo = 'Shougo/unite.vim'
depends = ['neomru.vim', 'tabpagebuffer.vim']
on_event = 'VimEnter'
hook_source = '''
	source $RC_PATH/plugins/unite.rc.vim
'''

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
	nnoremap <silent> <F2> :<C-u>Defx -toggle -listed -winwidth=50 -split=vertical -direction=topleft `expand('%:p:h')` -search=`expand('%:p')` -columns=git:mark:filename:type<CR>
	:imap <silent> <F2> <C-o>:<C-u>Defx -toggle -winwidth=50 -split=vertical -direction=topleft `expand('%:p:h')` -search=`expand('%:p')` -columns=git:mark:filename:type<CR>
'''
hook_source = '''
	source $RC_PATH/plugins/defx.rc.vim
'''

[[plugins]]
repo = 'kana/vim-niceblock'
on_map = {x = '<Plug>'}
hook_add = '''
	xmap I  <Plug>(niceblock-I)
	xmap A  <Plug>(niceblock-A)
'''

[[plugins]]
repo = 'vim-jp/vital.vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css', 'html', 'php']

[[plugins]]
repo = 'thinca/vim-qfreplace'
on_ft = ['unite', 'quickfix']

[[plugins]]
repo = 'thinca/vim-quickrun'
on_map = '<Plug>'
hook_add = 'nmap <silent> <Leader>r <Plug>(quickrun)'

[[plugins]]
repo = 'thinca/vim-ref'
on_map = {n = '<Plug>'}
hook_source = 'source $RC_PATH/plugins/ref.rc.vim'

[[plugins]]
repo = 'tsukkee/unite-tag'
on_source = 'unite.vim'

[[plugins]]
repo = 'kopischke/unite-spell-suggest'
on_source = 'unite.vim'

[[plugins]]
repo = 'mtscout6/vim-tagbar-css'
on_source = 'tagbar'

[[plugins]]
repo = 'ujihisa/neco-look'
on_source = ['deoplete.nvim']

[[plugins]]
repo = 'ujihisa/unite-colorscheme'
on_source = 'unite.vim'

[[plugins]]
repo = 'osyo-manga/unite-quickfix'
on_source = 'unite.vim'

[[plugins]]
repo = 'kana/vim-tabpagecd'
unite_sources = 'tab'

[[plugins]]
repo = 'godlygeek/csapprox'

[[plugins]]
repo = 'thinca/vim-guicolorscheme'

[[plugins]]
repo = 'bkad/CamelCaseMotion'
on_map = ['<Plug>CamelCaseMotion_w', '<Plug>CamelCaseMotion_b']

[[plugins]]
repo = 'syngan/vim-vimlint'
depends = 'ynkdir/vim-vimlparser'

# Operators
[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-operator-replace'
depends = 'kana/vim-operator-user'
on_map = [['nx', '<Plug>']]

[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = 'kana/vim-operator-user'
on_map = '<Plug>'

[[plugins]]
repo = 'chikatoike/concealedyank.vim'
on_map = [['x', '<Plug>(operator-concealedyank)']]

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'osyo-manga/vim-textobj-multiblock'
depends = 'kana/vim-textobj-user'
on_map = [['ox', '<Plug>']]

[[plugins]]
repo = 'AndrewRadev/sideways.vim'
on_map = [['ox', '<Plug>']]

[[plugins]]
repo = 'lambdalisue/vim-gita'
commands = 'Gita'

[[plugins]]
repo = 'lambdalisue/vim-gista'
on_map = {n = '<Plug>'}
hook_add = '''
  let g:gista#github_user = 'NemesisRE'
  let g:gista#directory = expand('$CACHE/gista')
'''

[[plugins]]
repo = 'shawncplus/phpcomplete.vim'
on_ft = ['php','ctp']

[[plugins]]
repo = 'ujihisa/unite-locate'
on_source = 'unite.vim'
unite_sources = 'locate'

[[plugins]]
repo = 'chrisbra/csv.vim'
on_ft = 'csv'
hook_add = '''
	filetype plugin indent on
'''

[[plugins]]
repo = 'spf13/PIV'
on_ft = ['php','ctp']
hook_add  = '''
	let g:DisableAutoPHPFolding=1
'''

[[plugins]]
repo = 'kovetskiy/vim-bash'
on_ft = 'sh'

[[plugins]]
repo = 'medihack/sh.vim'
on_ft = 'sh'
hook_add = '''
	let g:sh_indent_case_labels=1
'''

[[plugins]]
repo = 'vim-scripts/SQLComplete.vim'
on_ft = 'sql'

[[plugins]]
repo = 'violetyk/cake.vim'
on_ft = ['php','ctp']

[[plugins]]
repo = 'bigbrozer/vim-nagios'
on_ft = 'ruby'

[[plugins]]
repo = 'saltstack/salt-vim'
on_ft = ['salt','sls']

