[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'scwood/vim-hybrid'
hook_source = '''
	syntax on
	set background=dark
	colorscheme hybrid
'''

[[plugins]]
repo = 'mhinz/vim-startify'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-git'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-unimpaired'

[[plugins]]
repo = 'tpope/vim-ragtag'

[[plugins]]
repo = 'tpope/vim-repeat'
mappings = '.'

[[plugins]]
repo = 'mbbill/undotree'

[[plugins]]
repo = 'tomtom/tcomment_vim'
on_ft = 'all'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'mtscout6/vim-tagbar-css'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'pbrisbin/vim-mkdir'

[[plugins]]
repo = 'jmcantrell/vim-diffchanges'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'zhaocai/DirDiff.vim'

[[plugins]]
repo = 'edkolev/promptline.vim'

[[plugins]]
repo = 'ap/vim-css-color'

[[plugins]]
repo = 'vim-scripts/bufkill.vim'

[[plugins]]
repo = 'mhinz/vim-signify'

[[plugins]]
repo = 'int3/vim-extradite'
depends = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-rooter'
