[[plugins]]
repository = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repository = 'Shougo/neoyank.vim'

[[plugins]]
repository = 'mhinz/vim-startify'

[[plugins]]
repository = 'tpope/vim-endwise'

[[plugins]]
repository = 'tpope/vim-fugitive'

[[plugins]]
repository = 'tpope/vim-git'

[[plugins]]
repository = 'tpope/vim-surround'

[[plugins]]
repository = 'tpope/vim-unimpaired'

[[plugins]]
repository = 'tpope/vim-ragtag'

[[plugins]]
repository = 'tpope/vim-repeat'
mappings = '.'

[[plugins]]
repository = 'mbbill/undotree'

[[plugins]]
repository = 'Yggdroot/indentLine'

[[plugins]]
repository = 'tomtom/tcomment_vim'
filetypes = 'all'

[[plugins]]
repository = 'scrooloose/syntastic'

[[plugins]]
repository = 'godlygeek/tabular'

[[plugins]]
repository = 'junkblocker/unite-tasklist'

[[plugins]]
repository = 'majutsushi/tagbar'

[[plugins]]
repository = 'vim-airline/vim-airline'

[[plugins]]
repository = 'vim-airline/vim-airline-themes'

[[plugins]]
repository = 'airblade/vim-gitgutter'

[[plugins]]
repository = 'terryma/vim-multiple-cursors'

[[plugins]]
repository = 'mtscout6/vim-tagbar-css'

[[plugins]]
repository = 'bronson/vim-trailing-whitespace'

[[plugins]]
repository = 'kopischke/unite-spell-suggest'

[[plugins]]
repository = 'osyo-manga/unite-filetype'

[[plugins]]
repository = 'supermomonga/unite-kawaii-calc'

[[plugins]]
repository = 'gregsexton/MatchTag'

[[plugins]]
repository = 'vim-scripts/delimitMate.vim'

[[plugins]]
repository = 'xolox/vim-misc'

[[plugins]]
repository = 'xolox/vim-easytags'
depends = 'xolox/vim-misc'

[[plugins]]
repository = 'pbrisbin/vim-mkdir'

[[plugins]]
repository = 'jmcantrell/vim-diffchanges'

[[plugins]]
repository = 'rhysd/auto-neobundle'

[[plugins]]
repository = 'editorconfig/editorconfig-vim'

[[plugins]]
repository = 'zhaocai/DirDiff.vim'

[[plugins]]
repository = 'edkolev/promptline.vim'

[[plugins]]
repository = 'ap/vim-css-color'

[[plugins]]
repository = 'kopischke/vim-fetch'

[[plugins]]
repository = 'vim-scripts/bufkill.vim'

[[plugins]]
repository = 'mhinz/vim-signify'

[[plugins]]
repository = 'int3/vim-extradite'
depends = 'tpope/vim-fugitive'

[[plugins]]
repository = 'airblade/vim-rooter'

[[plugins]]
repository = 'blueyed/vim-colors-solarized'
unite_sources = 'colorscheme'

[[plugins]]
repository = 'Konfekt/FastFold'
